# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: James Clarke
description: >- # this means to ignore newlines until "baseurl:"
  baseurl: "" # the subpath of the site
url: "https://www.jhclarke.com" # the base hostname & protocol for the site
og_image: /assets/img/james.png
google_analytics: "UA-121636368-3"

header:
  pages:
    # - name: Work
    # - name: Notes
    # - name: Blog

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: (em spelled backwards)@jhclarke.com
      link: mailto:(em spelled backwards)@jhclarke.com
  follow:
    - name: LinkedIn
      link: https://linkedin.com/in/james-h-clarke-v/
    - name: GitHub
      link: https://github.com/jhclarke
    - name: Soundcloud
      link: https://soundcloud.com/jclarke44
    # - name: RSS
    #   link: /feed.xml

# Build settings
kramdown:
  input: GFM
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
